name = "digitalroot9"
main = "src/index.js"
compatibility_date = "2026-09-09"
routes = [
  { pattern = "digitalroot9.com/*", zone_name = "digitalroot9.com" }
]

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*"]

[observability]
enabled = true

[[send_email]]
name = "EMAIL"
remote = true
allowed_sender_addresses = ["enquiries@digitalroot9.com"]
allowed_destination_addresses = ["patrick@digitalroot9.com"]
